# Generated by Django 4.2 on 2023-07-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('linkedId', models.IntegerField(blank=True, null=True)),
                ('linkprecedence', models.TextField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
